### PR TITLE
Rename items

### PR DESCRIPTION
**Pull request by gftabor**
Allows double clicking on items in the side menu and renaming them. The accompanying files are renamed as well. Paths that are renamed are updated in every auton that uses them.

#21

### CODE REVIEW

**Comment by arjungandhi** [comment]
there is an issue with it displaying the incorrect name it displays as a bunch of weird characters.

**Comment by gftabor** [comment]
@arjungandhi try with that new commit. I just added a print to help with debugging. This is the behavior on my machine so I am not sure.  Maybe a different OS thing?

screenshot from 2018-07-11 12-08-52

**Comment by gftabor** [comment]
@arjungandhi try with that new commit. I just added a print to help with debugging. This is the behavior on my machine so I am not sure.  Maybe a different OS thing?

screenshot from 2018-07-11 12-08-52

**Comment by gftabor** [comment]
This is continued on #31

**Pull request closed without merging**
